Repository LedgerHQ/ledger-live-common, pull requests merged in 2022-04, with the labels that each got.

#1841 Add ETH goerli
  cli/src/live-common-setup-base.ts
  package.json
  src/__tests__/test-helpers/setup.ts
  src/api/explorerConfig/index.ts
  src/appSupportsQuitApp.ts
  src/env.ts
  src/mock/account.ts
  tools/src/live-common-setup.js
  yarn.lock
Labels: feature ready

#1852 Family/crypto org
  src/families/crypto_org/js-buildTransaction.ts
  src/families/crypto_org/js-signOperation.ts
Labels: feature ready

#1805 [LIVE-1174] - Feature: Upgrade NFT Architecture
  cli/package.json
  cli/src/commands/sync.ts
  cli/yarn.lock
  src/account/formatters.ts
  src/account/serialization.ts
  src/api/Ethereum.ts
  src/bridge/jsHelpers.ts
  src/families/ethereum/bridge/js.ts
  src/families/ethereum/modules/erc1155.ts
  src/families/ethereum/modules/erc721.ts
  src/families/ethereum/nft.merging.unit.test.ts
  src/families/ethereum/nftMetadataResolver.ts
  src/families/ethereum/synchronisation.ts
  src/nft/NftMetadataProvider/index.tsx
  src/nft/NftMetadataProvider/types.ts
  src/nft/helpers.ts
  src/nft/nftId.ts
  src/nft/support.ts
  src/types/account.ts
  src/types/bridge.ts
  src/types/nft.ts
Labels: feature ready

#1847 Bugfix/bitcoin js ll tecsupport 1152 bitcoincashadd fix
  src/families/bitcoin/logic.ts
  src/families/bitcoin/specs.ts
  src/families/bitcoin/transaction.ts
Labels: feature ready

#1864 Replace all deprecated uses of open(deviceId) with withDevice
  src/bridge/jsHelpers.ts
  src/families/bitcoin/js-signOperation.ts
  src/families/crypto_org/js-signOperation.ts
  src/families/elrond/js-signOperation.ts
  src/families/polkadot/js-signOperation.ts
  src/families/ripple/bridge/js.ts
  src/families/stellar/js-signOperation.ts
  src/families/tron/bridge/js.ts
Labels: feature ready

#1863 [LIVE-1911][LIVE-1912] Feature - Add collection name resolver to eth familly
  src/api/Ethereum.ts
  src/families/ethereum/bridge/js.ts
  src/families/ethereum/modules/erc721.ts
  src/families/ethereum/nftMetadataResolver.ts
  src/families/ethereum/nftResolvers.ts
  src/nft/NftMetadataProvider/index.tsx
  src/nft/NftMetadataProvider/types.ts
  src/nft/helpers.ts
  src/types/bridge.ts
  src/types/nft.ts
Labels: feature ready

#1892 LIVE-1994 [BTC family] fix account index undefined
  src/families/bitcoin/wallet-btc/storage/index.ts
Labels: HODL

#1851 hotfix(walletconnect): make the walletconnect compatible with all EIP-712 implementations
  src/walletconnect/index.ts
Labels: bug, important
